### ISSUE TITLE
Error on creating a Docker image

### ISSUE THREAD

**Issue by natschoman** [ztp-at/RKSV#5]
I tried to build an image with the containing Dockerfile  
`docker build -t "ztprenter:dep_test" .`
but I get the following error message:

> Step 12/17 : RUN cd /home/rksv/pyreg && su -c 'make env' rksv
>  ---> Running in 8e94186cffd4
> make: *** No rule to make target 'env'.  Stop.
> The command '/bin/sh -c cd /home/rksv/pyreg && su -c 'make env' rksv' returned a non-zero code: 2

What am I missing?

Forgot to mention that I am working on **macOS Sierra 10.12.6** with the following **Docker version**

> Client:
>  Version:      17.09.0-ce
>  API version:  1.32
>  Go version:   go1.8.3
>  Git commit:   afdb6d4
>  Built:        Tue Sep 26 22:40:09 2017
>  OS/Arch:      darwin/amd64
> 
> Server:
>  Version:      17.09.0-ce
>  API version:  1.32 (minimum version 1.12)
>  Go version:   go1.8.3
>  Git commit:   afdb6d4
>  Built:        Tue Sep 26 22:45:38 2017
>  OS/Arch:      linux/amd64
>  Experimental: true

**Comment by ztp-mino** [comment]
hmm, what branch of RKSV are you working on? master? can you check if the repo gets copied into `/home/rksv/pyreg` in the container? is the `Makefile` in there?

**Comment by HNieme** [comment]
I just wanted to mention that I could successfully complete the build in a debian 9 virtualbox vm, running docker version 17.09.0-ce, build afdb6d4
See:
https://pastebin.com/vnuAGUb1
Maybe this helps?

**Comment by natschoman** [comment]
Ups, copied just the Dockerfile in another DIR and tried the build from there :flushed:
Thanks for the fast response, works in the git-directory now.

**Comment by ztp-mino** [comment]
good, lmk if you have other problems

**Comment by natschoman** [comment]
Hi,
back then I only tried to create the Docker image - successfully.
Now, some days later, I wanted to run the image - without success.
Creation runs like in the pastebin of HNieme. But when I try to run the image nothing happens, seems that it just exits immediately:

```
> romi@ubuntu:~$ docker images
> REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> rksv                latest              460b2a36f07b        12 minutes ago      1.4GB
> ubuntu              16.04               20c44cd7596f        5 days ago          123MB
> romi@ubuntu:~$ docker ps -a
> CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
> 9974e36e36bb        rksv                "/bin/sh -c '/bin/ba…"   8 minutes ago       Exited (0) 6 minutes ago                       objective_payne
> 5a6ed2142669        05a3bd381fc2        "/hello"                 5 weeks ago         Exited (0) 5 weeks ago                         infallible_hermann
> romi@ubuntu:~$ docker start objective_payne
> objective_payne
> romi@ubuntu:~$ docker ps -a
> CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
> 9974e36e36bb        rksv                "/bin/sh -c '/bin/ba…"   9 minutes ago       Exited (0) 4 seconds ago                       objective_payne
> 5a6ed2142669        05a3bd381fc2        "/hello"                 5 weeks ago         Exited (0) 5 weeks ago                         infallible_hermann
> romi@ubuntu:~$ docker logs objective_payne
> romi@ubuntu:~$ 
> 
```
How should I run the image?
Thanks for your help.

**Comment by ztp-mino** [comment]
The image doesn't do anything on it's own, it just sets up an environment where you can use the scripts.

You should run the image interactively with `docker run -it <imagename>` which will give you a shell with the environment prepared. Then you need to copy or mount whatever data you need to verify into the container and lauch the scripts from there.

**Comment by natschoman** [comment]
Ok, I understand, that works.
One last question: Could you please give me a hint how to run the GUI with the X11 forwarding?

On my Mac I installed XQuartz and tried to run it with the docker-command like:
`docker run -e DISPLAY=192.168.0.120:0 -v /tmp/.X11-unix:/tmp/.X11-unix jess/firefox`
which opens the firefox from that image in an XQuartz-application-window.

But the same with rksv is not working, however I think I am on the wrong track (cause I have to start the rktool.py script, right?):
`docker run -e DISPLAY=192.168.0.120:0 -v /tmp/.X11-unix:/tmp/.X11-unix -it rksv`
That opens the shell with the prepared environment.

**Comment by ztp-mino** [comment]
Just start `rktool.py` in the shell that opens up? If all else fails, you can start the ssh server in the container (`systemctl start ssh` I think) and then connect to it from your host using X forwarding (the `-X` switch).

Note however, that the GUI is somewhat fragile and not feature complete. If you want to do more than verifying single receipts or small DEPs you should check out the [wiki](https://github.com/ztp-at/RKSV/wiki) on how to use the command line tools.

**Comment by natschoman** [comment]
Didn't manage to get the GUI to run but the scripts work perfectly. Thanks.
