### ISSUE TITLE
cython==0.24.1

### ISSUE THREAD

**Issue by halkosajtarevic** [ztp-at/RKSV#6]
Hallo!

Ich bekomm beim Versuch `make env` auszuführen den Fehler: 
`Collecting cython==0.24.1
  Could not find a version that satisfies the requirement cython==0.24.1 (from versions: )
No matching distribution found for cython==0.24.1
make: *** [.pyenv] Error 1
Makefile:75: recipe for target '.pyenv' failed
The command '/bin/sh -c cd /home/rksv/pyreg && su -c 'make env' rksv' returned a non-zero code: 2`

**Comment by ztp-mino** [comment]
Sorry für die lange Verzögerung!
Bei mir gehts... Cython 0.24.1 ist für Python 2.7 und Python 3.4/3.5 vorhanden. Welche Umgebung verwenden Sie?

**Comment by halkosajtarevic** [comment]
das Dockerfile - mit dem gehts nicht...

**Comment by ztp-mino** [comment]
Ich hab das Dockerfile grad bei mir selbst durchlaufen lassen... Funktioniert. Kann es sein, dass es sich um ein temporäres Problem gehandelt hat? Pip gibt z.B. auch diesen Fehler zurück, wenn es keine Internetverbindung gibt.

**Comment by halkosajtarevic** [comment]
scheint als ob es am firmen-ssl-zertifikat hängen würde - wget läuft durch - pip aber anscheinend nicht :/
vielen dank für den tipp!

**Comment by halkosajtarevic** [comment]
`RUN export PIP_CERT=/pfad/zum/zertifikat.pem` vor dem `make env` befehl hat mein problem behoben!

**Comment by ztp-mino** [comment]
passt, wunderbar
